# Generated by Django 4.2 on 2026-05-18 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Golf Tournament', max_length=200)),
                ('num_days', models.IntegerField(default=3)),
                ('num_holes', models.IntegerField(default=18)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#2563eb', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='golf.tournament')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('saisie_group', models.IntegerField(choices=[(1, 'Groupe 1'), (2, 'Groupe 2')], default=1)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='golf.team')),
            ],
            options={
                'ordering': ['team__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MatchDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('is_locked', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='golf.tournament')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('tournament', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='HoleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_points', models.FloatField(default=0)),
                ('team2_points', models.FloatField(default=0)),
                ('team1_best', models.IntegerField(blank=True, null=True)),
                ('team2_best', models.IntegerField(blank=True, null=True)),
                ('hole', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='golf.hole')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_results_t1', to='golf.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_results_t2', to='golf.team')),
            ],
        ),
        migrations.AddField(
            model_name='hole',
            name='match_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='golf.matchday'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strokes', models.IntegerField(blank=True, null=True)),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='golf.hole')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='golf.player')),
            ],
            options={
                'unique_together': {('hole', 'player')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='hole',
            unique_together={('match_day', 'number')},
        ),
    ]
